### ISSUE TITLE
Wonder how to run this program

### ISSUE THREAD

**Issue by xiaoerlaigeid** [Bonelab/FemurSegmentation#1]
Very impressive job! I wonder how to run this code. And this repo hasn't provided data and the command line parameters. Looking forward to your replay!

**Comment by Besler** [comment]
Apologies on such a long delay.

The parameters are embedded in the command line arguments: https://github.com/Bonelab/FemurSegmentation/blob/b2ce881b5a4c8297c35ee0a852dfb7fe49635f29/scripts/sheetness.py#L15

It is setup a bit special, but you can generally do the following:

1. Compile, be sure to download [GridCut](https://gridcut.com/)
2. Parameters are in the [sheetness](https://github.com/Bonelab/FemurSegmentation/blob/master/scripts/sheetness.py) and [periosteal_segmentation.py](https://github.com/Bonelab/FemurSegmentation/blob/master/scripts/periosteal_segmentation.py)
3. Run the C++ args as you please. The parameters are in the methods.

```bash
$ ./periosteal_segmentation # Periosteal segmentation
<InputFileName> <MaskFileName> <OutputSegmentation> <Lambda> <Sigma> <Label>
$ ./sheetness2 # Generates a sheetness image
<InputFileName> <OutputMask> <OutputMeasure> <SetEnhanceBrightObjects[0,1]> <NumberOfSigma> <MinSigma> <MaxSigma> <LowThreshold> <HighThreshold> <Weight>
```

You have to do the marking yourself, which I do with [ITK-SNAP](http://www.itksnap.org/pmwiki/pmwiki.php).
